repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests==2.31.0.20240311
          - types-beautifulsoup4==4.12.0.7
  - repo: local
    hooks:
      - id: pnpm-lint-check
        name: pnpm lint --check
        entry: pnpm
        language: system
        types: ["ts", "tsx", "javascript"]
        args: ["lint", "--check"]
        pass_filenames: false
